##
# Temperature Converter
#
# @file
# @version 0.1

CC=gcc
CFLAGS=-std=c99 -Wall -pedantic

all: calculate-age-in-seconds

calculate-age-in-seconds: calculate-age-in-seconds.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm calculate-age-in-seconds

# end
