##
# Temperature Converter
#
# @file
# @version 0.1

CC=gcc
CFLAGS=-std=c99 -Wall -pedantic

all: temperature-converter

temperature-converter: temperature-converter.c
	$(CC) $(CFLAGS) -o $@ $<

clean:
	rm temperature-converter

# end
